version: '3.1'
services:
  postgres:
    image: "postgres:16"
    container_name: "nodegmp-postgresql"
    shm_size: 128mb
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - type: tmpfs
        target: /dev/shm
        name: "postgres-db"
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
volumes:
  postgres-db:
