version: '3.1'
services:
  mongo:
    image: "mongodb/mongodb-community-server:latest"
    container_name: "nodegmp-nosql"
    restart: always
    environment:
      - MONGODB_INITDB_ROOT_USERNAME:root
      - MONGODB_INITDB_ROOT_PASSWORD:nodegmp
    ports:
      - 27017:21017
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
