version: '3.1'
services:
  mongo:
    image: "mongodb/mongodb-community-server:latest"
    container_name: "nodegmp-nosql"
    restart: always
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
