version: '3.1'
services:
  web:
    container_name: "node-app"
    build: .
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      -  MIKRO_ORM_DB_NAME=${POSTGRES_DB}
      -  MIKRO_ORM_USER=${POSTGRES_USER}
      -  MIKRO_ORM_PASSWORD=${POSTGRES_PASSWORD}
      -  MIKRO_ORM_HOST=postgres
    depends_on:
      - postgres
    networks:
      - node_app_network
  postgres:
    image: "postgres:16"
    container_name: "nodegmp-postgresql"
    shm_size: 128mb
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - type: tmpfs
        target: /dev/shm
        name: "postgres-db"
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
    networks:
      - node_app_network
volumes:
  postgres-db:
networks:
  node_app_network:
