version: '3'
services:
  mongo:
    image: "mongodb/mongodb-community-server:latest"
    container_name: "nodegmp-nosql"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=nodegmp
    ports:
      - '27017:21017'
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db:
